name: wts_task
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  provider: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.4
  bot_toast: ^4.1.3
  http: ^1.4.0
  flutter_svg: ^2.2.0
  carousel_slider: ^5.1.1
  pin_code_fields: ^8.0.1
  mask_text_input_formatter: ^2.9.0
  shimmer: ^3.0.0
  equatable: ^2.0.7
  talker: ^4.4.1
  talker_dio_logger: ^4.4.1
  talker_flutter: ^4.4.1
  logger: ^2.6.0
  go_router: ^16.0.0

dependency_overrides:
  source_gen: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  hive_generator: ^2.0.1



flutter:

  uses-material-design: true

  assets:
    - assets/images/the_shop_creative.svg
    - assets/images/the_shop_creative.jpg

  fonts:
    - family: PublicSans
      fonts:
        - asset: assets/fonts/public_sans/PublicSans-Regular.ttf
        - asset: assets/fonts/public_sans/PublicSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/public_sans/PublicSans-Italic.ttf
          style: italic
